name="espresense-artifact-proxy"
main="src/index.ts"
compatibility_date = "2022-07-18"
account_id="c72fc273edfb2236527b400b5463d663"
compatibility_flags = [
    "streams_enable_constructors",
    "transformstream_enable_standard_constructor"
]
